### ISSUE TITLE
Update crates.io version

### ISSUE THREAD

**Issue by tbillington** [rust-utility/cmake-parser#1]
Hey there!

I'm working on better [CMake support](https://github.com/tbillington/kondo/issues/120) in [kondo](https://github.com/tbillington/kondo), and one aspect I wanted to look into was getting the project name through the cmake `project` command. I was searching and found your library which looks like it can help!

Just wanted to check if you're intending to update the crates.io version in sync with this repo. If not that's totally fine, I can do a git dependency for now.

Cheers,
Trent

**Comment by kilork** [comment]
Hi, @tbillington 

Yeap, not a problem, I stopped working on this about a year ago because of problems with last commands on the list. Technically nothing prevents me from publishing intermediate version. If there would be a use case for it, I can finish support for other commands, at least to some degree.

**Comment by tbillington** [comment]
I don't think I need any other commands at this stage! I got [project working](https://github.com/tbillington/kondo/blob/9b48edb1b3fe2bc69b7c6e0abe96a49bf9ed67da/kondo-lib/src/project/cmake.rs#L35-L51).

I'm using the git dependency for now which is fine

**Comment by kilork** [comment]
@tbillington I published next alpha `0.1.0-alpha.1`, feel free to use it. If there is any issues or additional requirements, I would be glad to have them as input here.
